package com.github.jdemeulenaere.compose.driver.plugin

import org.gradle.api.Plugin
import org.gradle.api.initialization.Settings

internal class DriverSettingsPlugin : Plugin<Settings> {
    override fun apply(settings: Settings) {
        configureComposeDriverProject(settings)
    }
}

private fun configureComposeDriverProject(settings: Settings) {
    val extension =
        settings.extensions.create("composeDriver", DriverSettingsPluginExtension::class.java)
    settings.gradle.settingsEvaluated {
        val androidProjectPath =
            extension.androidProjectName.orNull?.let {
                settings.addProject(it, androidBuildFile(projectName = it))
            }
        val desktopProjectPath =
            extension.desktopProjectName.orNull?.let { settings.addProject(it, DESKTOP_BUILD_FILE) }

        check(androidProjectPath != null || desktopProjectPath != null) {
            "Compose Driver plugin was applied but neither composeDriver.desktopProjectName nor composeDriver.androidProjectName were set"
        }

        addDependencies(settings, androidProjectPath, desktopProjectPath)
    }
}

private fun Settings.addProject(projectName: String, buildFile: String): String {
    val projectPath = ":$projectName"
    val projectDir =
        this.rootProject.projectDir.resolve("build").resolve("compose-driver").resolve(projectName)

    // Set the content of the build file. Note that we don't dynamically configure the project
    // and its extensions here because this unfortunately leads to classpath issues between
    // settings and projects. Generating a build.gradle(.kts) file here works best.
    projectDir.mkdirs()
    projectDir.resolve("build.gradle.kts").writeText(buildFile)

    include(projectPath)
    project(projectPath).projectDir = projectDir
    return projectPath
}

private fun addDependencies(
    settings: Settings,
    androidProjectPath: String?,
    desktopProjectPath: String?,
) {
    settings.gradle.beforeProject {
        fun addDependency(path: String, projectPath: String) {
            project.logger.lifecycle("Added project $path as dependency to $desktopProjectPath")
            val targetProject = project(projectPath)
            if (targetProject.state.executed) {
                targetProject.dependencies.add("implementation", project(path))
            } else {
                targetProject.afterEvaluate { dependencies.add("implementation", project(path)) }
            }
        }

        if (path == desktopProjectPath || path == androidProjectPath) {
            return@beforeProject
        }

        project.plugins.withId("org.jetbrains.kotlin.plugin.compose") {
            val path = project.path
            project.plugins.withId("com.android.library") {
                androidProjectPath?.let { addDependency(path, it) }
            }
            project.plugins.withId("org.jetbrains.kotlin.jvm") {
                desktopProjectPath?.let { addDependency(path, it) }
            }
            project.plugins.withId("org.jetbrains.kotlin.multiplatform") {
                androidProjectPath?.let { addDependency(path, it) }
                desktopProjectPath?.let { addDependency(path, it) }
            }
        }
    }
}

private const val COMPOSABLE_PROPERTY = "compose.driver.composable"

private fun androidBuildFile(projectName: String): String {
    return $$"""
    /** This file was generated by the Compose Driver plugin. Do not edit. */
    import com.github.jdemeulenaere.compose.driver.plugin.GenerateAndroidTestClassTask
    
    plugins { id("com.android.library") }
    
    android {
        namespace = "com.github.jdemeulenaere.compose.driver.android"
        compileSdk = libs.versions.android.compileSdk.get().toInt()
    
        defaultConfig { testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner" }
    
        testOptions { unitTests { isIncludeAndroidResources = true } }
    }
    
    androidComponents {
        beforeVariants(selector().withBuildType("release")) { it.enable = false }
        beforeVariants(selector().all()) { it.androidTestEnabled = false }
    
        onVariants { variant ->
            variant.hostTests.forEach { (_, test) ->
                val variantName = variant.name.capitalize()
                val task =
                    tasks.register<GenerateAndroidTestClassTask>("generateTestClassFor$variantName") {
                        outputDir.set(layout.buildDirectory.dir("generated/source/test/$variantName"))
                    }
                test.sources.java!!.addGeneratedSourceDirectory(task, GenerateAndroidTestClassTask::outputDir)
            }
        }
    }
    
    dependencies {
        testImplementation(project(":compose-driver:driver-core"))
        testImplementation("androidx.test.ext:junit:1.3.0")
        testImplementation("org.robolectric:robolectric:4.16.1")
        debugImplementation("androidx.compose.ui:ui-test-manifest:1.10.0")
    }
    
    // Dynamically add the run task and configure tests to enable the server. Doing so allows to
    // normally run `./gradlew build` to build and test everything else without running the server.
    if (gradle.startParameter.taskNames.any { it == ":$$projectName:run" }) {
        afterEvaluate {
            val testDebugUnitTest =
                tasks.named<Test>("testDebugUnitTest") {
                    systemProperty("compose.driver.enabled", "true")
                    
                    val prop = "$$COMPOSABLE_PROPERTY"
                    System.getProperty(prop)?.let { systemProperty(prop, it) }
                }
            tasks.register("run") { dependsOn(testDebugUnitTest) }
        }
    }
    """
        .trimIndent()
}

private val DESKTOP_BUILD_FILE =
    """
    /** This file was generated by the Compose Driver plugin. Do not edit. */
    plugins { application }

    application { mainClass = "com.github.jdemeulenaere.compose.driver.MainKt" }

    dependencies {
        implementation(project(":compose-driver:driver-core"))
        implementation("org.slf4j:slf4j-simple:2.0.17")
    }

    // Forward the `$COMPOSABLE_PROPERTY` property to the `run` task.
    tasks.named<JavaExec>("run") {
        val prop = "$COMPOSABLE_PROPERTY"
        System.getProperty(prop)?.let { systemProperty(prop, it) }
    }

    // These tasks fail with Compose Multiplatform 1.10.0, disable them for now.
    tasks.named("distTar").configure { enabled = false }
    tasks.named("distZip").configure { enabled = false }
    """
        .trimIndent()
